# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Do NOT edit this file.  Edit dobuild.ps1
[System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSAvoidUsingWriteHost", "")]
param (
    [ValidateSet("Debug", "Release")]
    [string] $BuildConfiguration = "Debug",

    [ValidateSet("net8.0")]
    [string] $BuildFramework = "net8.0"
)

$script:ModuleName = 'Microsoft.PowerShell.NamedPipeConnection'
$script:SrcPath = Join-Path -Path $PSScriptRoot -ChildPath 'src'
$script:OutDirectory = Join-Path -Path $PSScriptRoot -ChildPath 'out'

$script:BuildConfiguration = $BuildConfiguration
$script:BuildFramework = $BuildFramework

. $PSScriptRoot/doBuild.ps1

if (-not (Test-Path $OutDirectory))
{
    $script:OutModule = New-Item -ItemType Directory -Path (Join-Path $OutDirectory $ModuleName)
}
else
{
    $script:OutModule = Join-Path $OutDirectory $ModuleName
}

Write-Verbose -Verbose -Message "Invoking DoBuild script"
DoBuild
Write-Verbose -Verbose -Message "Finished invoking DoBuild script"
